name: Docker pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    name: Docker Build & push
    runs-on: ubuntu-latest

    steps:
      -  name: Checkout code
         uses: actions/checkout@v3

      -  name: Log in to Docker Hub
         run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      -  name: Build Docker image
         run: docker build buildx --platform linux/amd64,linux/arm64 -t alensaleksandrs/misina_lv:latest --no-cache --push .